name: data-visualization-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas<3
  - seaborn
  - matplotlib
  - numpy
  - jupyterlab
  - notebook
  - ipykernel
  - geopandas
  - pygris
